In [2]:
import numpy as np
import pandas as pd
import os
import csv
import cv2
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score

In [1]:
import cv2

In [7]:
folder1=r"C:\Users\LENOVO\Desktop\CV_CP\Stair"
folder2=r"C:\Users\LENOVO\Desktop\CV_CP\NoStair"

In [4]:
i=0
for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    resultimage = np.zeros((280, 430))
   
    #normalizing the given image using normalize() function
    nimg = cv2.normalize(img,resultimage, 0, 255, cv2.NORM_MINMAX)
    
    #gray image
    gray = cv2.cvtColor(nimg, cv2.COLOR_BGR2GRAY)
    hist_image=cv2.equalizeHist(gray)
    
       
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('Str.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (581, 128)
descriptor shape  1  :  (436, 128)
descriptor shape  2  :  (276, 128)
descriptor shape  3  :  (595, 128)
descriptor shape  4  :  (447, 128)
descriptor shape  5  :  (305, 128)
descriptor shape  6  :  (490, 128)
descriptor shape  7  :  (358, 128)
descriptor shape  8  :  (301, 128)
descriptor shape  9  :  (270, 128)
descriptor shape  10  :  (74, 128)
descriptor shape  11  :  (64, 128)
descriptor shape  12  :  (381, 128)
descriptor shape  13  :  (241, 128)
descriptor shape  14  :  (543, 128)
descriptor shape  15  :  (408, 128)
descriptor shape  16  :  (305, 128)
descriptor shape  17  :  (82, 128)
descriptor shape  18  :  (58, 128)
descriptor shape  19  :  (490, 128)
descriptor shape  20  :  (377, 128)
descriptor shape  21  :  (72, 128)
descriptor shape  22  :  (63, 128)
descriptor shape  23  :  (101, 128)
descriptor shape  24  :  (117, 128)
descriptor shape  25  :  (396, 128)
descriptor shape  26  :  (827, 128)
descriptor shape  27  :  (602, 128)
descript

In [2]:
data1 = pd.read_csv(r'Str.csv',header=None,dtype='uint8')
#MemoryError: Unable to allocate 166. MiB for an array with shape (128, 169606) and data type float64,
#Double-precision floating-point format

data1=data1.astype(np.uint8) 
#as unit8 contain 1 byte(8bit) and ranges from 0 to 255
data1

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         28    0    0    0    0    0    0    3  178    9  ...    0   33    8   
1          3    0    0    0    0    0   21   72   71    0  ...    4    4   78   
2          0    1   15  127   36    0    0    0    8   12  ...    7    5   14   
3          0    0    1    4   11   46   14    5   20    1  ...    6   36    3   
4         24   49   24   19   18    2    0    0  133  103  ...    1   25   19   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1760443    0    2   11    0    0    0    0    0    0   12  ...    0    5   28   
1760444   61   16    0    0    0    0    0    8  180    3  ...    0    1    2   
1760445   49   61    0    0    0    0    0    0  151  151  ...    1    7    6   
1760446   48   36   11    5    1    0    0    0   25  100  ...   12   49   32   
1760447    0    0    0    0    0    0    0    0    8    0  ...  149   39    0   

         121  122  123  124  125  126  127  
0          9   23   67   31    2    2    4  
1         34    0    0    0    0    0    1  
2         43    9    6    9    9    5    1  
3          0    5  132   82    0    0    1  
4          2    0    2  149   15    0    8  
...      ...  ...  ...  ...  ...  ...  ...  
1760443   69   64   35    1    0    0    0  
1760444    1    0    6    2    0    0    0  
1760445    3    0    0    6   16    3    3  
1760446   33    0    1    2    3    2    3  
1760447   15  101    2    1   53   68    0  

[1760448 rows x 128 columns]

In [6]:
i=0
for filename in os.listdir(folder2):
    
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv('Nstr.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (76, 128)
descriptor shape  1  :  (740, 128)
descriptor shape  2  :  (133, 128)
descriptor shape  3  :  (697, 128)
descriptor shape  4  :  (1729, 128)
descriptor shape  5  :  (1219, 128)
descriptor shape  6  :  (1281, 128)
descriptor shape  7  :  (155, 128)
descriptor shape  8  :  (49, 128)
descriptor shape  9  :  (1444, 128)
descriptor shape  10  :  (657, 128)
descriptor shape  11  :  (785, 128)
descriptor shape  12  :  (965, 128)
descriptor shape  13  :  (423, 128)
descriptor shape  14  :  (1395, 128)
descriptor shape  15  :  (1060, 128)
descriptor shape  16  :  (633, 128)
descriptor shape  17  :  (469, 128)
descriptor shape  18  :  (582, 128)
descriptor shape  19  :  (767, 128)
descriptor shape  20  :  (1224, 128)
descriptor shape  21  :  (42, 128)
descriptor shape  22  :  (1194, 128)
descriptor shape  23  :  (538, 128)
descriptor shape  24  :  (540, 128)
descriptor shape  25  :  (902, 128)
descriptor shape  26  :  (487, 128)
descriptor shape  27  :  (133, 12

In [ ]:
data2= pd.read_csv(r'Nstr.csv',header=None,dtype='uint8')
data2=data2.astype(np.uint8)
data2

In [7]:
data=data1.append(data2)

In [9]:
csv_data=data.to_csv('Sift_Final.csv', mode='a', header=False,index=False)

In [8]:
data

0    1    2    3    4    5    6    7    8    9    ...  118  119  120  \
0         28    0    0    0    0    0    0    3  178    9  ...    0   33    8   
1          3    0    0    0    0    0   21   72   71    0  ...    4    4   78   
2          0    1   15  127   36    0    0    0    8   12  ...    7    5   14   
3          0    0    1    4   11   46   14    5   20    1  ...    6   36    3   
4         24   49   24   19   18    2    0    0  133  103  ...    1   25   19   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1473434    7    5    1    4   24   72   73   72    1    0  ...   14   20   10   
1473435    0    0    1    8    9    0    0    0    2    3  ...  133   87   39   
1473436    7    4   11    7    3    4    1    1   81    4  ...    4  105   16   
1473437    1    1    0    0    0    0    0    0   22    5  ...   48   54   15   
1473438    0    0    0    0    0    0    0    0    9    3  ...    1  126  111   

         121  122  123  124  125  126  127  
0          9   23   67   31    2    2    4  
1         34    0    0    0    0    0    1  
2         43    9    6    9    9    5    1  
3          0    5  132   82    0    0    1  
4          2    0    2  149   15    0    8  
...      ...  ...  ...  ...  ...  ...  ...  
1473434    0    0    1    0    0    2   16  
1473435   45   27    5    5   28   41   34  
1473436    2    0    2   15    5    4   20  
1473437    4    4   15   14   16   24   16  
1473438   15   12   11    3    1    0   61  

[3233887 rows x 128 columns]

# Kmeans

In [ ]:
kmeans = KMeans(n_clusters=5)
kmeans.fit(data)

In [4]:
import pickle

In [ ]:
filename = 'Kmeans_CL_5_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [5]:
pickle_in = open('Kmeans_CL_5_Model.sav','rb')
kmeans = pickle.load(pickle_in)
#pickle.dump(kmeans, open(filename, 'wb'))
pickle_in.close()

C:\Users\LENOVO\anaconda3\lib\site-packages\sklearn\base.py:310: UserWarning: Trying to unpickle estimator KMeans from version 1.0.1 when using version 0.24.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(


In [6]:
hist=np.histogram(kmeans.labels_,bins=[0,1,2,3,4,5])


print('histogram of trained kmeans')
print(hist,"\n")

histogram of trained kmeans
(array([802926, 439877, 928211, 477527, 612106], dtype=int64), array([0, 1, 2, 3, 4, 5])) 



In [ ]:
#folder1=r"D:/StrData/Str"
#folder2=r"D:\StrData\Nstr"

In [9]:
#performing kmeans prediction of the entire Staircase dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    
    #resize image
    resize=(280,430)
    img=cv2.resize(a,resize)
    
    #gray image
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    sift = cv2.xfeatures2d.SIFT_create()
    
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    a=kmeans.predict(array_double)
    
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    #k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('FinalStr.csv', mode='a',header=False,index=False)

In [10]:
#performing kmeans prediction of the entire Non_Staircase dataset with the pretrained kmeans model

#initialising i=1; as its the 2nd class
i=1
data=[]
k=0
for filename in os.listdir(folder2):
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    resize=(280,430)
    img=cv2.resize(a,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    if (array_double.any() == 0):
      continue

    a=kmeans.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    k=k+1
    
#convert Array to Dataframe and append to the list
Output = pd.DataFrame(data)
#add row class 
Output["Class"] = i 
csv_data=Output.to_csv('FinalNstr.csv', mode='a',header=False,index=False)

In [7]:
#Displaying the kmeans predicted data
print("Staircase")
dat1= pd.read_csv(r'FinalStr.csv',header=None)
print(dat1)

Staircase
        0    1    2    3    4  5
0     104  104  141   96  136  0
1     112   39  122   82   81  0
2      82   26  104   20   44  0
3     136   55  131  119  154  0
4     114   40  151   53   89  0
...   ...  ...  ...  ...  ... ..
2995   25    2   23    9   34  0
2996   44   52   47   41   87  0
2997   46   34   35   40   59  0
2998   15   21   19   19   20  0
2999   15   14   14   14   22  0

[3000 rows x 6 columns]


In [8]:
print("Non-Staircase")
dat2= pd.read_csv(r'FinalNstr.csv',header=None)
print(dat2)

Non-Staircase
        0    1    2    3    4  5
0      21    4   18    5   28  1
1     156  108  250  115  111  1
2      25   10   57    9   32  1
3     168   93  156   98  182  1
4     668  107  648  101  205  1
...   ...  ...  ...  ...  ... ..
2948  315  174  326  192  161  1
2949  304  130  342  125  123  1
2950  271  136  385  166  220  1
2951  254  120  258  154  179  1
2952  247  116  351  115  203  1

[2953 rows x 6 columns]


In [9]:
#appending All classes into 1 csv file

A=dat1.append(dat2)

csv_data=A.to_csv('FinalFV.csv', mode='a',header=False,index=False)

In [14]:
A

0    1    2    3    4  5
0     104  104  141   96  136  0
1     112   39  122   82   81  0
2      82   26  104   20   44  0
3     136   55  131  119  154  0
4     114   40  151   53   89  0
...   ...  ...  ...  ...  ... ..
2948  315  174  326  192  161  1
2949  304  130  342  125  123  1
2950  271  136  385  166  220  1
2951  254  120  258  154  179  1
2952  247  116  351  115  203  1

[5953 rows x 6 columns]

In [11]:
x = A.iloc[:,0:5].values

In [12]:
x

array([[104, 104, 141,  96, 136],
       [112,  39, 122,  82,  81],
       [ 82,  26, 104,  20,  44],
       ...,
       [271, 136, 385, 166, 220],
       [254, 120, 258, 154, 179],
       [247, 116, 351, 115, 203]], dtype=int64)

In [13]:
y = A.iloc[:,5].values

In [14]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [15]:
from sklearn.preprocessing import StandardScaler
DhoniS = StandardScaler()
Dhoni = DhoniS.fit_transform(x)

In [16]:
Dhoni

array([[-0.17415321,  0.43481672, -0.07265052,  0.23033832,  0.44752905],
       [-0.12732428, -0.48235776, -0.17323048,  0.03461979, -0.27754344],
       [-0.30293278, -0.66579266, -0.26851676, -0.8321337 , -0.76531947],
       ...,
       [ 0.8034008 ,  0.88634877,  1.21900795,  1.20893098,  1.55491247],
       [ 0.70388931,  0.66058275,  0.5467103 ,  1.04117224,  1.0144039 ],
       [ 0.66291399,  0.60414124,  1.03902275,  0.49595633,  1.33079916]])

In [17]:
from sklearn.decomposition import PCA

In [18]:
pca = PCA(n_components=None)
pca.fit(Dhoni)

PCA()

In [19]:
Bhumi = pca.transform(Dhoni)

In [20]:
Bhumi

array([[ 0.37426435, -0.48428615,  0.29098834, -0.12854308,  0.04697436],
       [-0.45321165,  0.1011175 , -0.08539285,  0.36600835, -0.01544575],
       [-1.25765248,  0.48628062, -0.21987412, -0.1294922 ,  0.0451478 ],
       ...,
       [ 2.52992998, -0.0939576 ,  0.52375789,  0.2028562 ,  0.26733421],
       [ 1.76720819, -0.2493905 ,  0.26484197,  0.26863136, -0.1274844 ],
       [ 1.84154121,  0.23479245,  0.62073131, -0.11045981,  0.23895338]])

In [21]:
Bhumi = pd.DataFrame(Bhumi)

In [22]:
Bhumi

0         1         2         3         4
0     0.374264 -0.484286  0.290988 -0.128543  0.046974
1    -0.453212  0.101118 -0.085393  0.366008 -0.015446
2    -1.257652  0.486281 -0.219874 -0.129492  0.045148
3     0.378274 -0.211369  0.565352  0.580104 -0.106891
4    -0.508149  0.356637  0.075223  0.055137  0.077520
...        ...       ...       ...       ...       ...
5948  2.567523 -0.521041 -0.396470  0.112146 -0.119479
5949  1.667604  0.272338 -0.473088 -0.142236  0.003713
5950  2.529930 -0.093958  0.523758  0.202856  0.267334
5951  1.767208 -0.249391  0.264842  0.268631 -0.127484
5952  1.841541  0.234792  0.620731 -0.110460  0.238953

[5953 rows x 5 columns]

In [23]:
Bhumi.shape

(5953, 5)

In [24]:
print(pca.explained_variance_ratio_) 

[0.75070127 0.14505228 0.07515531 0.02330586 0.00578529]


In [25]:
pca = PCA(n_components=3)
pca.fit(Dhoni)

PCA(n_components=3)

In [26]:
# save the model to disk
filename = 'PCA_3_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [27]:
Bhumi = pca.transform(Dhoni)

In [28]:
Bhumi

array([[ 0.37426435, -0.48428615,  0.29098834],
       [-0.45321165,  0.1011175 , -0.08539285],
       [-1.25765248,  0.48628062, -0.21987412],
       ...,
       [ 2.52992998, -0.0939576 ,  0.52375789],
       [ 1.76720819, -0.2493905 ,  0.26484197],
       [ 1.84154121,  0.23479245,  0.62073131]])

In [29]:
Bhumi.shape

(5953, 3)

In [30]:
print(pca.explained_variance_ratio_) 

[0.75070127 0.14505228 0.07515531]


In [31]:
Bhumi = pd.DataFrame(Bhumi)

In [36]:
Bhumi

0         1         2
0     0.374264 -0.484286  0.290988
1    -0.453212  0.101118 -0.085393
2    -1.257652  0.486281 -0.219874
3     0.378274 -0.211369  0.565352
4    -0.508149  0.356637  0.075223
...        ...       ...       ...
5948  2.567523 -0.521041 -0.396470
5949  1.667604  0.272338 -0.473088
5950  2.529930 -0.093958  0.523758
5951  1.767208 -0.249391  0.264842
5952  1.841541  0.234792  0.620731

[5953 rows x 3 columns]

In [32]:
B=pd.concat([Bhumi, pd.DataFrame(y)],axis=1)

In [33]:
B

0         1         2  0
0     0.374264 -0.484286  0.290988  0
1    -0.453212  0.101118 -0.085393  0
2    -1.257652  0.486281 -0.219874  0
3     0.378274 -0.211369  0.565352  0
4    -0.508149  0.356637  0.075223  0
...        ...       ...       ... ..
5948  2.567523 -0.521041 -0.396470  1
5949  1.667604  0.272338 -0.473088  1
5950  2.529930 -0.093958  0.523758  1
5951  1.767208 -0.249391  0.264842  1
5952  1.841541  0.234792  0.620731  1

[5953 rows x 4 columns]

In [34]:
csv_data=B.to_csv('FinalPCAFV.csv', mode='a',header=False,index=False)

# Training ,Testing & Classification

In [35]:
data= pd.read_csv(r'FinalPCAFV.csv',header=None)

data

0         1         2  3
0      0.374264 -0.484286  0.290988  0
1     -0.453212  0.101118 -0.085393  0
2     -1.257652  0.486281 -0.219874  0
3      0.378274 -0.211369  0.565352  0
4     -0.508149  0.356637  0.075223  0
...         ...       ...       ... ..
11901  2.567523 -0.521041 -0.396470  1
11902  1.667604  0.272338 -0.473088  1
11903  2.529930 -0.093958  0.523758  1
11904  1.767208 -0.249391  0.264842  1
11905  1.841541  0.234792  0.620731  1

[11906 rows x 4 columns]

In [36]:
#assigning x the columns from 1 to 128 for training
x = data.iloc[:,0:3].values
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = data.iloc[:,3]
print("Y values")
print(y)

X values
[[ 0.37426435 -0.48428615  0.29098834]
 [-0.45321165  0.1011175  -0.08539285]
 [-1.25765248  0.48628062 -0.21987412]
 ...
 [ 2.52992998 -0.0939576   0.52375789]
 [ 1.76720819 -0.2493905   0.26484197]
 [ 1.84154121  0.23479245  0.62073131]]
Y values
0        0
1        0
2        0
3        0
4        0
        ..
11901    1
11902    1
11903    1
11904    1
11905    1
Name: 3, Length: 11906, dtype: int64


In [37]:
#Dataset split into train and test with 80% Training and 20% Testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=0)

In [38]:
#Decision Tree Classifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model1 = DecisionTreeClassifier(max_depth=13)
filename = 'model1.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#training the model with the Training Variables 
model1.fit(x_train, y_train)
#predicting the traget variable using testing variables
y_pred1 = model1.predict(x_test)
#Results
print("Decision Tree Results")
print("Decision Tree Accuracy: ",accuracy_score(y_test, y_pred1)*100,"%")

Decision Tree Results
Decision Tree Accuracy:  82.99748110831234 %


In [39]:
#Recognition &Validation
#Assigning path with any any class image
data=[]
path=r"0.png"


#Repeated the process of image pre-processing and feature extraction
a=cv2.imread(path)
resize=(280,430)

#resize image
img=cv2.resize(a,resize)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

#initialise sift descriptor
sift = cv2.xfeatures2d.SIFT_create()
keypoints, descriptors = sift.detectAndCompute(gray, None)

#convert the descriptor array into a dataframe format
out=pd.DataFrame(descriptors)
print("Descriptor Shape:",out.shape)

#initialise Kmeans and create 5 clusters


#train the model for the features i.e. for all elements in the Dataframe
array_double = np.array(out, dtype=np.double)
a=kmeans.predict(array_double)

#get the values of the histogram for one image only for 5 clusters i.e. in 5 bins
#kmeans.labels_ give us the label vlaue of the feature that its clustered into
#hist will give the hostogram for all those vlaues
hist=np.histogram(a,bins=[0,1,2,3,4,5])

#append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
data.append(hist[0])

Output = pd.DataFrame(data)
print("Histogram:\n",Output)

Descriptor Shape: (121, 128)
Histogram:
     0   1   2   3   4
0  20  12  24  22  43


In [40]:
from sklearn.preprocessing import StandardScaler
MuktaS = StandardScaler()
Mukta = MuktaS.fit_transform(Output)

In [41]:
Mukta

array([[0., 0., 0., 0., 0.]])

In [42]:
Mukta.shape

(1, 5)

In [43]:
MB = pca.transform(Mukta)

In [44]:
MB.shape

(1, 3)

In [45]:
MB

array([[-2.60776837e-17, -2.56301047e-17,  6.74250975e-17]])

In [46]:
#prediction
y_pred1 = model1.predict(MB)

#prints the prediction of the class
print(y_pred1)

[1]


In [47]:
from sklearn.svm import SVC
DhoniSVM_LK = SVC(kernel='rbf')
Dhoni_LK = DhoniSVM_LK.fit(x_train, y_train)

In [48]:
filename = 'SVC_RBF_PCA_3.sav'
pickle.dump(Dhoni_LK, open(filename, 'wb'))

In [49]:
Dhoni_LK

SVC()

In [50]:
y_pred_LK = Dhoni_LK.predict(x_test)

In [51]:
y_pred_LK

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

In [52]:
from sklearn.metrics import confusion_matrix

In [53]:
confusion_matrix(y_test, y_pred_LK)

array([[903, 302],
       [358, 819]], dtype=int64)

In [54]:
from sklearn.metrics import accuracy_score

In [59]:
accuracy_score(y_test, y_pred_LK)

0.7229219143576826

In [56]:
y_pred1 = model1.predict(MB)

#prints the prediction of the class
print(y_pred1)

[1]


In [73]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
model3 = LogisticRegression(random_state = 0)
model3.fit(x_train, y_train)   
y_pred3 = model3.predict(x_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred3)
  
# print ("Confusion Matrix : \n", cm)
ac = accuracy_score(y_test,y_pred3)*100
ac

61.62888329135181

In [72]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
model2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
model2.fit(x_train, y_train) 
y_pred2 = model2.predict(x_test)
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred2)
ac = accuracy_score(y_test,y_pred2)*100
print(ac)

79.89084802686818


In [81]:
#Random Forest CLassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model4 = RandomForestClassifier(n_estimators=100, criterion='entropy', max_depth=None, min_samples_split=2,
                                min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='log2',
                                max_leaf_nodes=None, min_impurity_decrease=0.0, bootstrap=True, oob_score=False, 
                                n_jobs=None, random_state=2, verbose=0, warm_start=False, class_weight=None, 
                                ccp_alpha=0.0, max_samples=None)
filename = r'model4.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#training the model with the Training Variables 
model4.fit(x_train, y_train)
#predicting the traget variable using testing variables
y_pred4 = model4.predict(x_test)
y_predt = model4.predict(x_train)
#Results
print("RandomF Results")
print("RandomF Accuracy: ",accuracy_score(y_test, y_pred4)*100,"%")
print("RandomF Training Accuracy: ",accuracy_score(y_train, y_predt)*100,"%")

#print(y_pred4)

RandomF Results
RandomF Accuracy:  95.54995801847187 %
RandomF Training Accuracy:  100.0 %


In [75]:
matrix = confusion_matrix(y_test,y_pred_LK)
cm_df = pd.DataFrame(matrix, 
            columns = ['Predicted Negative', 'Predicted Positive'],
            index = ['Actual Negative', 'Actual Positive'])
# Showing the confusion matrix
cm_df
print('Confusion matrix : \n',cm_df)

Confusion matrix : 
                  Predicted Negative  Predicted Positive
Actual Negative                 903                 302
Actual Positive                 358                 819


In [76]:
TP = matrix[1][1]
TN = matrix[0][0]
FP = matrix[0][1]
FN = matrix[1][0]
    
# calculate the sensitivity
conf_sensitivity = (TP / float(TP + FN))
# calculate the specificity
conf_specificity = (TN / float(TN + FP))

print(f'Sensitivity: {round(conf_sensitivity,2)}') 
print(f'Specificity: {round(conf_specificity,2)}') 

Sensitivity: 0.7
Specificity: 0.75


In [77]:
matrix = classification_report(y_test,y_pred_LK,labels=[1,0])
print('Classification report : \n',matrix)

Classification report : 
               precision    recall  f1-score   support

           1       0.73      0.70      0.71      1177
           0       0.72      0.75      0.73      1205

    accuracy                           0.72      2382
   macro avg       0.72      0.72      0.72      2382
weighted avg       0.72      0.72      0.72      2382



In [58]:
forest = model4.predict(MB)
print(forest)

[1]
